### ISSUE TITLE
SSL certification failed when grabbing song

### ISSUE THREAD

**Issue by baddles** [mrwnwttk/scdl#2]
![image](https://user-images.githubusercontent.com/33995791/66538940-9caceb80-eb50-11e9-9f05-aee490b4a53d.png)

**Comment by mrwnwttk** [comment]
I created a separate branch called "ssl-fix" that attempts to fix this. I can't replicate this issue at home unfortunately. Can you please report back and say whether or not this commit fixed it?

**Comment by baddles** [comment]
![image](https://user-images.githubusercontent.com/33995791/66680896-bad33280-ec9b-11e9-8a38-ade236246697.png)
Well it worked. Though it yells for stuffs, but it downloaded.

**Comment by mrwnwttk** [comment]
I've never seen it throw syntax warnings before, I'll fix that later. For now you can also just run the script as `python3 -W ignore ./scdl -p`

The man page for find on macOS says that it supports the --name parameter as well as --size and --delete, I'd have to set up a VM in order to try and replicate this. Which version of macOS are you using?

**Comment by mrwnwttk** [comment]
Pushed two commits that should fix both the warnings as well as the errors related to find. Please let me know if it works for you :)

**Comment by baddles** [comment]
![image](https://user-images.githubusercontent.com/33995791/66709718-1a146e00-ed94-11e9-94cd-61763715e972.png)
Normal download works fine for me, but premium isn't tho.

**Comment by mrwnwttk** [comment]
You don’t have ffmpeg, therefore you can’t download the file from the .m3u8 and therefore the size check fails.
